/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_win_main (void)
{
  GtkWidget *win_main;
  GtkWidget *vbox7;
  GtkWidget *menubar1;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *imagemenuitem1;
  GtkWidget *image29;
  GtkWidget *imagemenuitem2;
  GtkWidget *image30;
  GtkWidget *imagemenuitem3;
  GtkWidget *view1;
  GtkWidget *view1_menu;
  GtkWidget *menu_hex;
  GtkWidget *menuitem6;
  GtkWidget *menuitem6_menu;
  GtkWidget *imagemenuitem4;
  GtkWidget *image31;
  GtkWidget *vbox8;
  GtkWidget *frame7;
  GtkWidget *alignment12;
  GtkWidget *hbox9;
  GtkWidget *combobox1;
  GtkWidget *button6;
  GtkWidget *image19;
  GtkWidget *label21;
  GtkWidget *frame8;
  GtkWidget *alignment13;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *label22;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  win_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (win_main), _("MemWatch by [volk]"));
  gtk_window_set_position (GTK_WINDOW (win_main), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (win_main), 300, 400);
  gtk_window_set_icon_name (GTK_WINDOW (win_main), "gtk-zoom-fit");
  gtk_window_set_gravity (GTK_WINDOW (win_main), GDK_GRAVITY_CENTER);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (win_main), vbox7);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox7), menubar1, FALSE, FALSE, 0);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  imagemenuitem1 = gtk_image_menu_item_new_with_mnemonic (_("_Save"));
  gtk_widget_show (imagemenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), imagemenuitem1);
  gtk_tooltips_set_tip (tooltips, imagemenuitem1, _("Save current configuration"), NULL);
  gtk_widget_add_accelerator (imagemenuitem1, "activate", accel_group,
                              GDK_s, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image29 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image29);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (imagemenuitem1), image29);

  imagemenuitem2 = gtk_image_menu_item_new_with_mnemonic (_("_Load"));
  gtk_widget_show (imagemenuitem2);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), imagemenuitem2);
  gtk_tooltips_set_tip (tooltips, imagemenuitem2, _("Load a configuration"), NULL);
  gtk_widget_add_accelerator (imagemenuitem2, "activate", accel_group,
                              GDK_o, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image30 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image30);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (imagemenuitem2), image30);

  imagemenuitem3 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (imagemenuitem3);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), imagemenuitem3);
  gtk_tooltips_set_tip (tooltips, imagemenuitem3, _("Quit the application"), NULL);

  view1 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (view1);
  gtk_container_add (GTK_CONTAINER (menubar1), view1);

  view1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (view1), view1_menu);

  menu_hex = gtk_check_menu_item_new_with_mnemonic (_("Hex"));
  gtk_widget_show (menu_hex);
  gtk_container_add (GTK_CONTAINER (view1_menu), menu_hex);
  gtk_tooltips_set_tip (tooltips, menu_hex, _("Show integers in HEX"), NULL);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem6);

  menuitem6_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menuitem6_menu);

  imagemenuitem4 = gtk_image_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (imagemenuitem4);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), imagemenuitem4);
  gtk_tooltips_set_tip (tooltips, imagemenuitem4, _("About your's truly"), NULL);
  gtk_widget_add_accelerator (imagemenuitem4, "activate", accel_group,
                              GDK_F1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image31 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image31);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (imagemenuitem4), image31);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (vbox7), vbox8, TRUE, TRUE, 0);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox8), frame7, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame7), GTK_SHADOW_NONE);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (frame7), alignment12);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment12), 0, 0, 12, 0);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox9);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_box_pack_start (GTK_BOX (hbox9), combobox1, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), "");

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox9), button6, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button6, _("Refresh the list of processes"), NULL);

  image19 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (button6), image19);

  label21 = gtk_label_new (_("<b>Target process</b>"));
  gtk_widget_show (label21);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label21);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox8), frame8, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_NONE);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (frame8), alignment13);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment13), 0, 0, 12, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (alignment13), scrolledwindow1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tooltips_set_tip (tooltips, treeview1, _("List of monitored variables"), NULL);

  label22 = gtk_label_new (_("<b>Variables</b>"));
  gtk_widget_show (label22);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label22);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox7), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) win_main, "delete_event",
                    G_CALLBACK (on_win_main_delete_event),
                    NULL);
  g_signal_connect ((gpointer) menubar1, "activate_current",
                    G_CALLBACK (on_menubar_load),
                    NULL);
  g_signal_connect ((gpointer) imagemenuitem1, "activate",
                    G_CALLBACK (on_winmain_menu_save_activate),
                    NULL);
  g_signal_connect ((gpointer) imagemenuitem2, "activate",
                    G_CALLBACK (on_winmain_menu_load_activate),
                    NULL);
  g_signal_connect ((gpointer) imagemenuitem3, "activate",
                    G_CALLBACK (on_menu_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_hex, "activate",
                    G_CALLBACK (on_menu_hex_activate),
                    NULL);
  g_signal_connect ((gpointer) imagemenuitem4, "activate",
                    G_CALLBACK (on_menu_about_activate),
                    NULL);
  g_signal_connect ((gpointer) combobox1, "realize",
                    G_CALLBACK (on_process_list_realize),
                    NULL);
  g_signal_connect ((gpointer) combobox1, "changed",
                    G_CALLBACK (on_process_list_changed),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_update_proc_list_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_varview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "popup_menu",
                    G_CALLBACK (on_varview_popup_menu),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "realize",
                    G_CALLBACK (on_varview_realize),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "button_press_event",
                    G_CALLBACK (on_varview_button_press),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_main, win_main, "win_main");
  GLADE_HOOKUP_OBJECT (win_main, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (win_main, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (win_main, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (win_main, menuitem5_menu, "menuitem5_menu");
  GLADE_HOOKUP_OBJECT (win_main, imagemenuitem1, "imagemenuitem1");
  GLADE_HOOKUP_OBJECT (win_main, image29, "image29");
  GLADE_HOOKUP_OBJECT (win_main, imagemenuitem2, "imagemenuitem2");
  GLADE_HOOKUP_OBJECT (win_main, image30, "image30");
  GLADE_HOOKUP_OBJECT (win_main, imagemenuitem3, "imagemenuitem3");
  GLADE_HOOKUP_OBJECT (win_main, view1, "view1");
  GLADE_HOOKUP_OBJECT (win_main, view1_menu, "view1_menu");
  GLADE_HOOKUP_OBJECT (win_main, menu_hex, "menu_hex");
  GLADE_HOOKUP_OBJECT (win_main, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (win_main, menuitem6_menu, "menuitem6_menu");
  GLADE_HOOKUP_OBJECT (win_main, imagemenuitem4, "imagemenuitem4");
  GLADE_HOOKUP_OBJECT (win_main, image31, "image31");
  GLADE_HOOKUP_OBJECT (win_main, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (win_main, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (win_main, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (win_main, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (win_main, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (win_main, button6, "button6");
  GLADE_HOOKUP_OBJECT (win_main, image19, "image19");
  GLADE_HOOKUP_OBJECT (win_main, label21, "label21");
  GLADE_HOOKUP_OBJECT (win_main, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (win_main, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (win_main, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (win_main, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (win_main, label22, "label22");
  GLADE_HOOKUP_OBJECT (win_main, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (win_main, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (win_main), accel_group);

  return win_main;
}

GtkWidget*
create_win_about (void)
{
  GtkWidget *win_about;
  GtkWidget *vbox6;
  GtkWidget *label24;
  GtkWidget *button5;
  GtkWidget *alignment11;
  GtkWidget *hbox7;
  GtkWidget *image14;
  GtkWidget *label20;

  win_about = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (win_about), _("About"));
  gtk_window_set_position (GTK_WINDOW (win_about), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (win_about), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (win_about), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (win_about), TRUE);
  gtk_window_set_icon_name (GTK_WINDOW (win_about), "gtk-about");

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (win_about), vbox6);

  label24 = gtk_label_new (_("<b>Memory Monitor by [volk]</b>\n<b>v 0.1</b>\n\nReport all bugs and feature requests to\nMartin K. Schreder\n<span foreground=\"blue\">mkschreder@gmail.com</span>"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox6), label24, TRUE, TRUE, 0);
  gtk_widget_set_size_request (label24, 272, 96);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_CENTER);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (vbox6), button5, FALSE, FALSE, 0);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button5), alignment11);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox7);

  image14 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox7), image14, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox7), label20, FALSE, FALSE, 0);

  g_signal_connect_swapped ((gpointer) button5, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (win_about));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_about, win_about, "win_about");
  GLADE_HOOKUP_OBJECT (win_about, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (win_about, label24, "label24");
  GLADE_HOOKUP_OBJECT (win_about, button5, "button5");
  GLADE_HOOKUP_OBJECT (win_about, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (win_about, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (win_about, image14, "image14");
  GLADE_HOOKUP_OBJECT (win_about, label20, "label20");

  return win_about;
}

GtkWidget*
create_win_addptr (void)
{
  GtkWidget *win_addptr;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox5;
  GtkWidget *frame5;
  GtkWidget *alignment5;
  GtkWidget *table5;
  GtkWidget *label2;
  GtkWidget *label10;
  GtkWidget *addptr_location;
  GtkWidget *label7;
  GtkWidget *addptr_description;
  GtkWidget *value_type;
  GtkWidget *label13;
  GtkWidget *frame3;
  GtkWidget *alignment3;
  GtkWidget *addptr_values;
  GtkWidget *label11;
  GtkWidget *hbox1;
  GtkWidget *btn_winaddrptr_add_location;
  GtkWidget *alignment7;
  GtkWidget *hbox3;
  GtkWidget *image10;
  GtkWidget *label15;
  GtkWidget *btn_winaddptr_cancel;
  GtkWidget *alignment8;
  GtkWidget *hbox4;
  GtkWidget *image11;
  GtkWidget *label16;
  GtkWidget *dialog_action_area1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_addptr = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (win_addptr), _("Add Memory Location"));
  gtk_window_set_modal (GTK_WINDOW (win_addptr), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (win_addptr), 300, 400);
  gtk_window_set_icon_name (GTK_WINDOW (win_addptr), "gtk-add");
  gtk_window_set_skip_pager_hint (GTK_WINDOW (win_addptr), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (win_addptr), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (win_addptr)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox5, TRUE, TRUE, 0);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox5), frame5, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame5), GTK_SHADOW_NONE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame5), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  table5 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (alignment5), table5);

  label2 = gtk_label_new (_("Type"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table5), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label10 = gtk_label_new (_("Location"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table5), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  addptr_location = gtk_entry_new ();
  gtk_widget_show (addptr_location);
  gtk_table_attach (GTK_TABLE (table5), addptr_location, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, addptr_location, _("Location of this variable inside foregn process"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (addptr_location), 9679);

  label7 = gtk_label_new (_("Description"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table5), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  addptr_description = gtk_entry_new ();
  gtk_widget_show (addptr_description);
  gtk_table_attach (GTK_TABLE (table5), addptr_description, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, addptr_description, _("Description that apears beside the value in the main window"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (addptr_description), 9679);

  value_type = gtk_combo_box_new_text ();
  gtk_widget_show (value_type);
  gtk_table_attach (GTK_TABLE (table5), value_type, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label13 = gtk_label_new (_("<b>Location Properties</b>"));
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label13);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox5), frame3, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (frame3), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 0, 0, 12, 0);

  addptr_values = gtk_tree_view_new ();
  gtk_widget_show (addptr_values);
  gtk_container_add (GTK_CONTAINER (alignment3), addptr_values);
  gtk_tooltips_set_tip (tooltips, addptr_values, _("Available presets (Right click to add)"), NULL);

  label11 = gtk_label_new (_("<b>Alternative Values</b>"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label11);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox1, FALSE, FALSE, 0);

  btn_winaddrptr_add_location = gtk_button_new ();
  gtk_widget_show (btn_winaddrptr_add_location);
  gtk_box_pack_start (GTK_BOX (hbox1), btn_winaddrptr_add_location, TRUE, TRUE, 0);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_winaddrptr_add_location), alignment7);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox3);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox3), image10, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox3), label15, FALSE, FALSE, 0);

  btn_winaddptr_cancel = gtk_button_new ();
  gtk_widget_show (btn_winaddptr_cancel);
  gtk_box_pack_start (GTK_BOX (hbox1), btn_winaddptr_cancel, TRUE, TRUE, 0);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btn_winaddptr_cancel), alignment8);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox4);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox4), image11, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox4), label16, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (win_addptr)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  g_signal_connect ((gpointer) win_addptr, "delete_event",
                    G_CALLBACK (on_win_addptr_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) addptr_location, "focus_out_event",
                    G_CALLBACK (on_addptr_location_focus_out),
                    NULL);
  g_signal_connect ((gpointer) addptr_location, "realize",
                    G_CALLBACK (on_addptr_location_realize),
                    NULL);
  g_signal_connect ((gpointer) addptr_description, "focus_out_event",
                    G_CALLBACK (on_addptr_description_focus_out),
                    NULL);
  g_signal_connect ((gpointer) addptr_description, "realize",
                    G_CALLBACK (on_addptr_description_realize),
                    NULL);
  g_signal_connect ((gpointer) value_type, "changed",
                    G_CALLBACK (on_value_type_changed),
                    NULL);
  g_signal_connect ((gpointer) value_type, "realize",
                    G_CALLBACK (on_value_type_realize),
                    NULL);
  g_signal_connect ((gpointer) addptr_values, "realize",
                    G_CALLBACK (on_addptr_values_realize),
                    NULL);
  g_signal_connect ((gpointer) addptr_values, "button_press_event",
                    G_CALLBACK (on_addptr_values_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) btn_winaddrptr_add_location, "clicked",
                    G_CALLBACK (on_btn_winaddrptr_add_location_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_winaddptr_cancel, "clicked",
                    G_CALLBACK (on_btn_winaddptr_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_addptr, win_addptr, "win_addptr");
  GLADE_HOOKUP_OBJECT_NO_REF (win_addptr, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (win_addptr, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (win_addptr, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (win_addptr, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (win_addptr, table5, "table5");
  GLADE_HOOKUP_OBJECT (win_addptr, label2, "label2");
  GLADE_HOOKUP_OBJECT (win_addptr, label10, "label10");
  GLADE_HOOKUP_OBJECT (win_addptr, addptr_location, "addptr_location");
  GLADE_HOOKUP_OBJECT (win_addptr, label7, "label7");
  GLADE_HOOKUP_OBJECT (win_addptr, addptr_description, "addptr_description");
  GLADE_HOOKUP_OBJECT (win_addptr, value_type, "value_type");
  GLADE_HOOKUP_OBJECT (win_addptr, label13, "label13");
  GLADE_HOOKUP_OBJECT (win_addptr, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (win_addptr, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (win_addptr, addptr_values, "addptr_values");
  GLADE_HOOKUP_OBJECT (win_addptr, label11, "label11");
  GLADE_HOOKUP_OBJECT (win_addptr, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (win_addptr, btn_winaddrptr_add_location, "btn_winaddrptr_add_location");
  GLADE_HOOKUP_OBJECT (win_addptr, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (win_addptr, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (win_addptr, image10, "image10");
  GLADE_HOOKUP_OBJECT (win_addptr, label15, "label15");
  GLADE_HOOKUP_OBJECT (win_addptr, btn_winaddptr_cancel, "btn_winaddptr_cancel");
  GLADE_HOOKUP_OBJECT (win_addptr, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (win_addptr, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (win_addptr, image11, "image11");
  GLADE_HOOKUP_OBJECT (win_addptr, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (win_addptr, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT_NO_REF (win_addptr, tooltips, "tooltips");

  return win_addptr;
}

GtkWidget*
create_win_value (void)
{
  GtkWidget *win_value;
  GtkWidget *dialog_vbox2;
  GtkWidget *frame2;
  GtkWidget *vbox3;
  GtkWidget *alignment2;
  GtkWidget *table2;
  GtkWidget *label6;
  GtkWidget *value_value;
  GtkWidget *label5;
  GtkWidget *value_description;
  GtkWidget *label23;
  GtkWidget *value_hotkey;
  GtkWidget *hbox2;
  GtkWidget *winvalue_value_add;
  GtkWidget *alignment9;
  GtkWidget *hbox5;
  GtkWidget *image12;
  GtkWidget *label17;
  GtkWidget *winvalue_value_cancel;
  GtkWidget *alignment10;
  GtkWidget *hbox6;
  GtkWidget *image13;
  GtkWidget *label18;
  GtkWidget *label4;
  GtkWidget *dialog_action_area2;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_value = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (win_value), _("Value Properties"));
  gtk_window_set_icon_name (GTK_WINDOW (win_value), "gtk-add");
  gtk_window_set_type_hint (GTK_WINDOW (win_value), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (win_value)->vbox;
  gtk_widget_show (dialog_vbox2);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), frame2, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame2), vbox3);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_box_pack_start (GTK_BOX (vbox3), alignment2, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  table2 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment2), table2);

  label6 = gtk_label_new (_("Value"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  value_value = gtk_entry_new ();
  gtk_widget_show (value_value);
  gtk_table_attach (GTK_TABLE (table2), value_value, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, value_value, _("Preset value"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (value_value), 9679);

  label5 = gtk_label_new (_("Description  "));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  value_description = gtk_entry_new ();
  gtk_widget_show (value_description);
  gtk_table_attach (GTK_TABLE (table2), value_description, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, value_description, _("Name of the preset as it would apear in context menu of main window"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (value_description), 9679);

  label23 = gtk_label_new (_("Hotkey"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table2), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  value_hotkey = gtk_entry_new ();
  gtk_widget_show (value_hotkey);
  gtk_table_attach (GTK_TABLE (table2), value_hotkey, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, value_hotkey, _("Global shortcut"), NULL);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, TRUE, TRUE, 0);

  winvalue_value_add = gtk_button_new ();
  gtk_widget_show (winvalue_value_add);
  gtk_box_pack_start (GTK_BOX (hbox2), winvalue_value_add, TRUE, TRUE, 0);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (winvalue_value_add), alignment9);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox5);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox5), image12, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox5), label17, FALSE, FALSE, 0);

  winvalue_value_cancel = gtk_button_new ();
  gtk_widget_show (winvalue_value_cancel);
  gtk_box_pack_start (GTK_BOX (hbox2), winvalue_value_cancel, TRUE, TRUE, 0);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (winvalue_value_cancel), alignment10);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox6);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox6), image13, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("<b>Value properties</b>"));
  gtk_widget_show (label4);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  dialog_action_area2 = GTK_DIALOG (win_value)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  g_signal_connect ((gpointer) value_value, "focus_out_event",
                    G_CALLBACK (on_value_value_focus_out_event),
                    NULL);
  g_signal_connect ((gpointer) value_value, "realize",
                    G_CALLBACK (on_value_value_realize),
                    NULL);
  g_signal_connect ((gpointer) value_description, "focus_out_event",
                    G_CALLBACK (on_value_description_focus_out_event),
                    NULL);
  g_signal_connect ((gpointer) value_description, "realize",
                    G_CALLBACK (on_value_description_realize),
                    NULL);
  g_signal_connect ((gpointer) value_hotkey, "focus_in_event",
                    G_CALLBACK (on_value_hotkey_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) value_hotkey, "focus_out_event",
                    G_CALLBACK (on_value_hotkey_focus_out_event),
                    NULL);
  g_signal_connect ((gpointer) value_hotkey, "realize",
                    G_CALLBACK (on_value_hotkey_realize),
                    NULL);
  g_signal_connect ((gpointer) winvalue_value_add, "clicked",
                    G_CALLBACK (on_winvalue_value_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) winvalue_value_cancel, "clicked",
                    G_CALLBACK (on_winvalue_value_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_value, win_value, "win_value");
  GLADE_HOOKUP_OBJECT_NO_REF (win_value, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (win_value, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (win_value, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (win_value, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (win_value, table2, "table2");
  GLADE_HOOKUP_OBJECT (win_value, label6, "label6");
  GLADE_HOOKUP_OBJECT (win_value, value_value, "value_value");
  GLADE_HOOKUP_OBJECT (win_value, label5, "label5");
  GLADE_HOOKUP_OBJECT (win_value, value_description, "value_description");
  GLADE_HOOKUP_OBJECT (win_value, label23, "label23");
  GLADE_HOOKUP_OBJECT (win_value, value_hotkey, "value_hotkey");
  GLADE_HOOKUP_OBJECT (win_value, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (win_value, winvalue_value_add, "winvalue_value_add");
  GLADE_HOOKUP_OBJECT (win_value, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (win_value, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (win_value, image12, "image12");
  GLADE_HOOKUP_OBJECT (win_value, label17, "label17");
  GLADE_HOOKUP_OBJECT (win_value, winvalue_value_cancel, "winvalue_value_cancel");
  GLADE_HOOKUP_OBJECT (win_value, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (win_value, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (win_value, image13, "image13");
  GLADE_HOOKUP_OBJECT (win_value, label18, "label18");
  GLADE_HOOKUP_OBJECT (win_value, label4, "label4");
  GLADE_HOOKUP_OBJECT_NO_REF (win_value, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT_NO_REF (win_value, tooltips, "tooltips");

  return win_value;
}

