/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_main (void);
GtkWidget* create_win_about (void);
GtkWidget* create_win_addptr (void);
GtkWidget* create_win_value (void);
