/*
-----------------------------------------------------------------------------
This source file is part of MemWatch (An application to watch memory inside a
foregin process in real time) 

For the latest info, see http://www.schreder.nu/

Copyright (c) 2008 Martin K. Schreder <mkschreder@gmail.com>

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation;

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along
with this program; if not, write to the Free Software Foundation, Inc., 59
Temple Place - Suite 330, Boston, MA 02111-1307, USA, or go to
http://www.gnu.org/copyleft/gpl.txt.
-----------------------------------------------------------------------------
*/


/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "main.h"


GtkWidget *gWinAddPointer;
GtkWidget *gWinMain;

static Profile gsProfile;

void util_create_popup_menu(menu_item_t *items, int count){
	GtkWidget *menu, *menuitem;
	int c;

	menu = gtk_menu_new();
	
	for(c = 0; c < count; c++){
		GtkWidget *image = gtk_image_new_from_stock(items[c].icon, GTK_ICON_SIZE_MENU);
		gtk_widget_show(image);
		menuitem = gtk_image_menu_item_new_with_mnemonic(items[c].name);
		gtk_image_menu_item_set_image(GTK_IMAGE_MENU_ITEM(menuitem), image);
		g_signal_connect(menuitem, "activate", (GCallback)items[c].callback,items[c].data);
		gtk_menu_shell_append(GTK_MENU_SHELL(menu), menuitem);
	}
	gtk_widget_show_all(menu);
	gtk_menu_popup(GTK_MENU(menu), NULL, NULL, NULL, NULL,
									 0, gdk_event_get_time(0));
}

int on_idle(gpointer ptr){
	// Update gui with latest data
	winmain_update_data();
	return TRUE;
}

#ifdef _WIN32
#include <windows.h>
int WINAPI WinMain(      
    HINSTANCE hInstance,
    HINSTANCE hPrevInstance,
    LPSTR lpCmdLine,
    int nCmdShow
	){
		char *argv[] = {"none","none"};
		int argc = 1;
#else
int
main (int argc, char *argv[])
{
#endif
	memset(&gsProfile, 0, sizeof(gsProfile));

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  sys_init();

  gtk_set_locale ();

  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gWinMain = create_win_main ();
	g_object_set_data(G_OBJECT(gWinMain), "profile", (gpointer)&gsProfile);
  
	gtk_widget_show (gWinMain);
	
	gWinAddPointer = create_win_addptr();
	
	g_timeout_add(100, on_idle, 0);

	winmain_init();
  gtk_main ();

  sys_finish();

  return 0;
}

